### ISSUE TITLE
How to import key file to Sophos XG

### ISSUE THREAD

**Issue by andreapx** [vchrizz/ovpn-to-apc#3]
Hi, on the XG the path /var/chroot-openvpn/etc/ is not present.
Do you know how to import the key otherwise?

**Comment by vchrizz** [comment]
Hi,
as this is for (now older) Astaro/Sophos UTM firwalls, where it is possible to upload those specific .apc files, I fear that this won't work on the new XG series, as they don't accept .apc files, as import-file for openvpn connections, do they?
Not sure though, I'm just assuming, I might be wrong.
