### ISSUE TITLE
Trying to convert ProtonVPN ovpn file fails with printf error

### ISSUE THREAD

**Issue by SchiSchi2** [vchrizz/ovpn-to-apc#4]
Hello,

I'm currently trying to convert a OVPN config from ProtonVPN but get the following error:
./ovpn-to-apc.sh: line 330: printf: missing hex digit for \x
./ovpn-to-apc.sh: line 370: printf: missing hex digit for \x

Any ideas how to fix this?

Regards
Sebastian

**Comment by SchiSchi2** [comment]
Ok, found the problem... there is no client certificate inside the ovpn config :(
To bad...

**Comment by vchrizz** [comment]
Hi, thanks, so I guess this issue can be closed?
Else feel free to reopen :)
